import {useEffect,useState} from 'react'; import axios from 'axios'; import {DatabaseZap} from 'lucide-react';
import QueryInput from './components/QueryInput'; import SQLDisplay from './components/SQLDisplay'; import ResultsTable from './components/ResultsTable'; import QueryHistory from './components/QueryHistory'; import SchemaExplorer from './components/SchemaExplorer';
const api=axios.create({baseURL:import.meta.env.VITE_API_URL||'/api',timeout:30000});
export default function App(){
 const [prompt,setPrompt]=useState('');const [sql,setSql]=useState('');const [results,setResults]=useState(null);const [rowCount,setRowCount]=useState(0);const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState('');const [tables,setTables]=useState([]);const [history,setHistory]=useState(()=>{try{return JSON.parse(localStorage.getItem('nl2sql-history'))||[]}catch{return[]}});
 useEffect(()=>{api.get('/schema').then(r=>setTables(r.data.tables)).catch(()=>setError('Could not load the database schema. Is the backend running?'))},[]);
 useEffect(()=>localStorage.setItem('nl2sql-history',JSON.stringify(history)),[history]);
 async function generate(){setError('');setBusy('generate');setResults(null);try{let r=await api.post('/generate-query',{prompt});setSql(r.data.sql)}catch(e){setError(e.response?.data?.error||'Could not generate SQL.')}finally{setBusy('')}}
 async function execute(){setError('');setBusy('execute');try{let r=await api.post('/execute-query',{sql});setResults(r.data.results);setRowCount(r.data.rowCount);setMessage(r.data.message||'');setHistory(h=>[{id:Date.now(),prompt,sql:r.data.sql,results:r.data.results,rowCount:r.data.rowCount,message:r.data.message||''},...h].slice(0,25))}catch(e){setError(e.response?.data?.error||'Could not execute the query.')}finally{setBusy('')}}
 function restore(x){setPrompt(x.prompt);setSql(x.sql);setResults(x.results);setRowCount(x.rowCount);setMessage(x.message);setError('')}
 function csv(){let cols=Object.keys(results[0]||{}),esc=v=>'"'+String(v??'').replaceAll('"','""')+'"',data=[cols.map(esc).join(','),...results.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download='query-results.csv';a.click();URL.revokeObjectURL(a.href)}
 return <><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-5 py-4"><span className="rounded-xl bg-forest p-2 text-white"><DatabaseZap size={22}/></span><div><h1 className="font-bold tracking-tight">Natural Language to SQL Engine</h1><p className="text-xs text-slate-500">Ask questions. Inspect SQL. Explore your data.</p></div></div></header><main className="mx-auto grid max-w-7xl gap-5 p-5 lg:grid-cols-[240px_minmax(0,1fr)_260px]"><aside className="order-2 lg:order-1"><SchemaExplorer tables={tables}/></aside><div className="order-1 space-y-5 lg:order-2"><QueryInput value={prompt} onChange={setPrompt} onGenerate={generate} loading={busy==='generate'}/>{error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<SQLDisplay sql={sql} onChange={setSql} onExecute={execute} loading={busy==='execute'}/><ResultsTable results={results} rowCount={rowCount} message={message} onExport={csv}/></div><aside className="order-3"><QueryHistory items={history} onSelect={restore} onClear={()=>setHistory([])}/></aside></main></>}

